q1_answers = [
    "I begin tucking him into bed and he tells me, “Daddy check for monsters under my bed.” I look underneath for his amusement and see him, another him, under the bed, staring back at me quivering and whispering, “Daddy there’s somebody on my bed.” — justAnotherMuffledVo",
    "The doctors told the amputee he might experience a phantom limb from time to time. Nobody prepared him for the moments though, when he felt cold fingers brush across his phantom hand. — Gagege",
    "I can’t move, breathe, speak or hear and it’s so dark all the time. If I knew it would be this lonely, I would have been cremated instead. — Graboid27",
    "Don’t be scared of the monsters, just look for them. Look to your left, to your right, under your bed, behind your dresser, in your closet but never look up, she hates being seen. — AnarchistWaffles",
    "I woke up to hear knocking on glass. At first, I though it was the window until I heard it come from the mirror again. — therealhatman",
    "They celebrated the first successful cryogenic freezing. He had no way of letting them know he was still conscious. — KnowsGooderThanYou",
    "She wondered why she was casting two shadows. Afterall, there was only a single lightbulb. — pgan91",
    "It sat on my shelf, with thoughtless porcelain eyes and the prettiest pink doll dress I could find. Why did she have to be born still? — Horseseverywhere",
    "The grinning face stared at me from the darkness beyond my bedroom window. I live on the 14th floor. — bentreflection",
    "There was a picture in my phone of me sleeping. I live alone. — guztaluz",
    "Working the night shift alone tonight. There is a face in the cellar staring at the security camera. — hctet",
    "They delivered the mannequins in bubble wrap. From the main room I begin to hear popping. — Mikeyseventyfive",
    "You wake up. She doesn’t. — tuskedlemon",
    "She asked why I was breathing so heavily. I wasn’t. — Calamitosity",
    "You get home, tired after a long day’s work and ready for a relaxing night alone. You reach for the light switch, but another hand is already there. — madamimadamimadam",
    "My daughter won’t stop crying and screaming in the middle of the night. I visit her grave and ask her to stop, but it doesn’t help. — skuppy",
    "Day 312. Internet still not working. — fluffyponyza",
    "You start to drift off into a comfortable sleep when you hear your name being whispered. You live alone. — anonymous_abc",
    "I needed to quickly run a SQL command to update a single row in an Oracle DB table at work. To my horror, it came back with “–2,378,231 rows affected.” — waysafe",
    "You’re laying in bed and with your feet dangling out of the covers. You feel a hand grab your feet. — HesusMendez",
    "The funeral attendees never came out of the catacombs. Something locked the crypt door from the inside. — TLFMOD",
    "My wife woke me up last night to tell me there was an intruder in our house. She was murdered by an intruder 2 years ago. — The_D_String",
    "The officer finally got back to me. The call was coming from inside the house.",
    "I was having a pleasant dream when what sounded like hammering woke me. After that, I could barely hear the muffled sound of dirt covering the coffin over my own screams. — vigridarena",
    "The last man on Earth sat alone in a room. There was a knock at the door. — Scry67",
    "After working a hard day I came home to see my girlfriend cradling our child. I didn’t know which was more frightening, seeing my dead girlfriend and stillborn child, or knowing that someone broke into my apartment to place them there. — cobaltcollapse",
    "You hear your mom calling you into the kitchen. As you are heading down the stairs you hear a whisper from the closet saying “Don’t go down there honey, I heard it too.” — comparativelysane",
    "I never go to sleep. But I keep waking up. — genetically_witless",
    "Nurse’s Note: Born 7 pounds 10 ounces, 18 inches long, 32 fully formed teeth. Silent, always smiling. — ichokedcheryltunt",
    "She went upstairs to check on her sleeping toddler. The window was open and the bed was empty. — Aerron",
    "The longer I wore it the more it grew on me. She had such pretty skin. — blaqkmagick",
    "You hear the scream across the hallway, but your eyes won’t open and you can’t move. — dkmino",
    "Being the first to respond to a fatal car accident is always the most traumatic thing I see as a police officer. But today, when the crushed body of the little dead child boy strapped in his car seat opened his eyes and giggled at me when I tried to peel him out of the wreckage, I immediately knew that today would be my last day on the force. — scabbycakes",
    "I looked out my window. The stars had gone away. — Owllette",
    "“I can’t sleep” she whispered, crawling into bed with me. I woke up cold, clutching the dress she was buried in. — VaultKid321",
    "I just saw my reflection blink. — marino1310",
    "I kiss my wife and daughter goodnight before I go to sleep. When I wake up, I’m in a padded room and the nurses tell me it was just a dream. — StoryTellerBob",
    "The pairs of emaciated eyes outnumber the single round in my gun. With pleading tears falling on her doll’s hair, I point the barrel at my last surviving daughter. — yoshkow",
    "I peeked outside. The pizza delivery guy is at the door, but I didn’t order a pizza — and definitely not from someone wearing a pig mask.",
    "My mother has been screaming at the front door for hours now. She’s not happy that I killed her with my bare hands.",
    "I have a friend named Charlie. I’m playing at his house but it’s cold down here in the basement, I wonder when Charlie will let me go home.",
    "If you get scared at night, don’t keep your eyes closed for too long. There’s a reason you’re scared, and now you can’t see it approach.",
    "I used a Ouija board yesterday, but I only asked one question and put it away. I got my answer today — written in blood on my ceiling.",
    "The wailing from the baby monitor just won’t stop. Problem is, my daughter is with her mother this weekend… over 200 miles away.",
    "Grandpa died smoking a cigar in his favorite chair. We got a new one but from the ash marks he leaves behind he has a new favorite chair.",
    "My husband woke me up by kissing my cheek when he got home late. This morning I checked my phone — he stayed with a friend last night.",
    "I like to sing in the shower sometimes. When I got out of the last one, the fogged-up mirror read “YOU HAVE A LOVELY VOICE” — I live alone.",
    "My wife just ran in to ask me if I was okay because she could hear my terrible coughing fit from across the house. I wasn’t coughing.",
    "The upstairs neighbors are awfully noisy. I told my landlord… it’s been vacant for months.",
    "For sale: like-new engagement ring, barely worn, came right off her finger. Finger also for sale for the right offer.",
    "I had a dream that a man was watching me sleep from outside my bedroom window. When I woke up, I found footprints… inside, next to my bed.",
    "My TV keeps turning on by itself. It’s annoying, but what’s more worrisome is how it only shows footage of me standing in my living room.",
    "My girlfriend is scared of horror movies. They make her paranoid, which can be tricky when I’m watching her through her living room window.",
    "I found a new bottle of my best friend’s favorite scotch on the kitchen counter today. He died in a drunk driving accident six years ago.",
    "It’s nice that my grandmother calls to check on me, but if she wants to communicate from the other side I wish she wouldn’t scream so much.",
    "My boyfriend has a collection he’s very proud of. He never told me that he’s been collecting souvenirs from the girlfriends he murdered.",
    "I have a recurring dream I’m murdered by a man I’d never met. I thought it was stupid until I went on a blind date and saw him at the table.",
    "My mom told me she had the best time playing with my little sister today. My sister went missing in 2002 — they found her body in 2006.",
    "The knife, it slices — just like butter I tried to be a loving mother. -littlemisssassy",
    "I can’t move, breathe, speak or hear and it’s so dark all day round. I should have been cremated, and not buried in the ground.",
    "I just saw the children playing, admiring how high they have swung. But others tell me they’re just swaying in the wind where they were hung.",
    "I was always told not to play with my food, as it is a blessing to eat. However I’m one to tease my meals, and killing is always a treat.",
    "Read this after the day is nigh. And tonight you might possibly die.",
    "I was never more scared or more filled filled with dread, Than the night the police found, her dismembered head.",
    "As I played in the basement, Mother called me upstairs. From behind me, She whispered, ‘Don’t go up there.’",
    "I watched you play whilst at the park. I’ll come to your house when the day goes dark.",
    "I had guests over today, they seemed to be really nice, so I introduced my hobby; it’s quite technical, you see, and I’m no good with words, so I had to show them. I really think my skills are improving; I almost didn’t have to break any bones this time, and I do like way they hang there, all strung up, an occasional whimper dripping past their mutilated lips like so much blood.",
    "I travel here and there so suddenly, and never make a sound. Slaying quickly, quietly, swiftly; Just don’t turn around.",
    "And from the grave, where my father was put And hand reached up and grabbed my foot.",
    "I saw the children playing, watched how high they swung. Their bodies swaying side to side, while silently they hung. ",
    "Roses are red, violets are blue. There is someone right behind you.",
    "You’re the prettiest person that I ever saw, I’d so love to snack on your eyeballs, quite raw."
]