q2_answers = [
    "I saw it with my own third eye.",
    "Watched it happen myself",
    "I saw it with my own one eye.",
    "I saw it with my own second eye.",
    "I saw it with my own fourth eye.",
    "I saw it with my own fifth eye.",
    "I saw it with my own sixth eye.",
    "I saw it with my own seventh eye.",
    "I saw it with my own eighth eye.",
    "I saw it with my own ninth eye.",
    "My 17th cousin told me about it.",
    "My mom saw it happened with her own eyes",
    "It happened to me.",
    "Man were lost, were super lost!",
    "I'm a lead farmer mother fucker!",
    "Hell nah, I ain't pee on nat girl. No no listen, here's the story she was in the way when I was peeing she walked past.",
    "I don't read the script. The script reads me.",
    "Shut the fuck up & let me do my job!",
    "Man, I don't drop character 'till I done the DVD commentary.",
    "Yes. But we are trained actors.",
    "To be a moron, to be moronical. To be the dumbest mother fucker who ever lived.",
    "Oh okay, Flaming Dragon, fuck face. First take a big step back and literally FUCK YOUR OWN FACE!",
    "You spank that ass, Les!",
    "What do YOU mean, you people?",
    "Hey, Alpa. If you get me some drugs I will totally suck your cock. Stroke the shaft, cradle the balls, swallow the gravy! C'mon man, let's do this!",
    "I know who I am! I'm a dude playing a dude disguised as another dude!",
    "It was like pistol whipping a blind kid.",
    "Man, everybody's gay once in a while.",
    "I'm sorry a dingo ate your baby.",
    "Let me get this straight. You want me to let my client of 15 years, one of my best friends, die in the jungle alone, for some money and a G5?",
    "You kick in the door to my house all ants in your pants, sucking my left nut to get a TiVo scrap for the 3rd runner-up 'sexiest man alive' 1998... And you're asking if I'm SERIOUS?",
    "I need some dudes up here that speak American, God damn it. He's making a fucking sweater back here. I'm trying to put Tiger Balm on this jungles nuts."
]