q3_answers = [
    "Dr. Rick Sanchez",
    "Dr. Nick",
    "Dr. Miranda Bailey",
    "Dr. Michaela Quinn",
    "Dr. Fraiser Crane",
    "Dr. Leonard H. McCoy",
    "Dr. John Carter",
    "Dr. John Dorian",
    "Dr. Doogie Howser",
    "Dr. Gregory House",
    "Dr. Stephen Strange",
    "Dr. Xavier",
    "Dr. Sheldon Cooper",
    "Dr. Eric Gablehauser",
    "Dr. Leonard Hofstadter",
    "Dr. Rajesh Koothrappali",
    "Dr. Leslie Winkle",
    "Dr. Bernadette Rostenkowski",
    "Dr. Amy Farrah Fowler",
    "Dr. Lisa Cuddy",
    "Dr. Allison Cameron",
    "Dr. Jessica Adams",
    "Dr. Lawrence Kutner"
]